dist: trusty
language: node_js
sudo: required
branches:
  only:
  - master
  - develop
  - travis_fix
  - /^feature\/.*/
notifications:
  email:
    recipients:
      - ci.report@ost.com
    on_success: always
    on_failure: always
node_js:
  - "8.12"
install:
  - npm install
before_script:
  - ./tools/runGanacheCli.sh </dev/null 1>/dev/null 2>&1 &
script:
  - npm run compile
  - sleep 10s
  - npm run test
after_script:
  - kill $(ps aux | grep 'ganache-cli' | awk '{print $2}')
